import puppeteer from "puppeteer-core";
const CHROME = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome";
const browser = await puppeteer.launch({ executablePath: CHROME, headless: "new", args: ["--no-sandbox", "--hide-scrollbars"] });
const page = await browser.newPage();
await page.setViewport({ width: 390, height: 844, deviceScaleFactor: 1 });
await page.goto("http://localhost:4322/der-ycat/", { waitUntil: "networkidle2" });
await page.click("#navToggle");
await new Promise((r) => setTimeout(r, 900));
await page.screenshot({ path: "/tmp/m_navopen.png" });
console.log("m_navopen.png captured");
await browser.close();
